name: CI/CD Frontend

on:
  push:
    branches:
      - master

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend-project/service-web-app

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: cd frontend-project/service-web-app && npm install

    - name: Test Angular app
      run: cd frontend-project/service-web-app && npm test

    backend-test:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: backend-project/microservices

    - name: Publish to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password:  ${{ secrets.DOCKER_PASSWORD }}
        repository: sa0ki/microservices-project
        tags: latest
