spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:4200"
            allowed-headers:
              - "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
  application:
    name: gateway-service
  config:
      import: optional:configserver:http://localhost:9090/gateway-service/default
server:
  port: 8080