name: CI/CD Backend

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: 17
          
      - name: Unit tests
        run: |
          mvn -B test --file backend-project/microservices/pom.xml
          mvn -B test --file backend-project/microservices/config-service/pom.xml
          mvn -B test --file backend-project/microservices/customer-service/pom.xml
          mvn -B test --file backend-project/microservices/inventory-service/pom.xml


      - name: Build the application
        run: |
          cd backend-project/microservices/
          mvn clean 
          mvn -B package --file pom.xml
          cd config-service/
          mvn clean 
          mvn -B package --file pom.xml
          cd ../customer-service/
          mvn clean 
          mvn -B package --file pom.xml
          cd ../inventory-service/
          mvn clean 
          mvn -B package --file pom.xml

          
